import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Books - Search',
  description: 'Generated by create next app',
}

export default function SearchLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <>{children}</>
}
