import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="">
          <div className="flex justify-between items-center px-6 h-20">
            <div className="flex items-center gap-x-1">
              <img src="/logo.svg" width={24} />
              <div className="text-xl font-medium text-[#1c2b33]">Books</div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
