import Link from 'next/link'
import Image from 'next/image'
import type { Metadata } from 'next'
import FirstView from '@/components/root/section-firstview'
import ParallaxSection from '@/components/root/section-slider'
import SearchSection from '@/components/root/section-search'
import StackSection from '@/components/root/section-stack'
import PreviewSection from '@/components/root/section-preview'
import LibrarySection from '@/components/root/section-library'

export const metadata: Metadata = {
  title: 'Books - Home',
  description: 'Generated by create next app',
}

export default function RootPage() {
  return (
    <div className="w-full overflow-x-hidden">
      <FirstView />
      <ParallaxSection />
      <div className="bg-gradient-to-b from-white to-[#fafafa] pb-[100px]">
        <SearchSection />
        <LibrarySection />
      </div>
      <div className="bg-gradient-to-b from-white to-[#fafafa]">
        <StackSection />
        <PreviewSection />
      </div>
    </div>
  )
}
