import Link from 'next/link'
import Image from 'next/image'
import type { Metadata } from 'next'
import Carousel from '@/components/root/carousel'
import SectionTitle from '@/components/root/section-title'
import { Section } from '@/components/root/section'
import Accordion from '@/components/root/accordion'
import SlideToLeft from '@/components/root/book-slider'
import { SlideToRight } from '@/components/root/book-slider'

export const metadata: Metadata = {
  title: 'Books - Home',
  description: 'Generated by create next app',
}

export default function RootPage() {
  return (
    <>
      <Section>
        <div className="my-10">
          <h1 className="text-center text-[24px] font-semibold">Book Search App</h1>
          <h2 className="text-center text-[52px] font-bold">どんな本も見つける</h2>
          <p className="text-center text-[18px] text-gray-600">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, repellendus sit! Reprehenderit, et nam necessitatibus fugiat nulla a quae
            deserunt. Porro, aliquam cupiditate! Non tenetur asperiores laboriosam inventore numquam tempora.
          </p>
        </div>
        <div className="flex flex-col gap-y-4">
          <SlideToLeft />
          <SlideToRight />
        </div>
      </Section>
      <Section>
        <SectionTitle title="ちょっとした機能" />
        <Accordion />
      </Section>
      <Section>
        <SectionTitle title="たくさんの本を見つけます。" />
        <div className="flex items-center justify-center lg:h-[600px]">
          <div className="relative">
            <img src="/macpro.jpg" />
            <img src="/book-sample.png" className="absolute right-0 top-0 w-40 overflow-hidden rounded-lg border border-gray-100" />
            <img src="/book-sample.png" className="absolute right-0 top-0 w-40 overflow-hidden rounded-lg border border-gray-100" />
            <img src="/book-sample.png" className="absolute right-0 top-0 w-40 overflow-hidden rounded-lg border border-gray-100" />
            <img src="/book-sample.png" className="absolute right-0 top-0 w-40 overflow-hidden rounded-lg border border-gray-100" />
            <img src="/book-sample.png" className="absolute left-64 top-20 w-40 overflow-hidden rounded-lg border border-gray-100" />
            <img src="/book-sample.png" className="absolute left-[10rem] top-0 w-40 overflow-hidden rounded-lg border border-gray-100" />
            <img src="/book-sample.png" className="absolute bottom-10 left-0 w-40 overflow-hidden rounded-lg border border-gray-100" />
            <img src="/book-sample.png" className="absolute bottom-2 left-40 w-40 overflow-hidden rounded-lg border border-gray-100" />
          </div>
        </div>
      </Section>
      <Section backgroundColor="bg-[#fafafa]">
        <SectionTitle title="使用技術を紹介します。" />
        <Carousel />
      </Section>
      <Section>
        <div className="mx-auto flex max-w-2xl gap-x-6">
          <div className="w-1/2 rounded-lg bg-gray-100 px-6 py-8">
            <Router title="GitHub" url="https://github.com/daxchx/book-search-app">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, maxime ipsum! Natus corrupti temporibus facilis at, odit voluptatibus officiis
              numquam. Porro, ab odio! Alias blanditiis ipsum, sed non voluptate vero.
            </Router>
          </div>
          <div className="w-1/2 rounded-lg bg-gray-100 p-6">
            <Router title="Google Books API" url="https://developers.google.com/books?hl=ja">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, maxime ipsum! Natus corrupti temporibus facilis at, odit voluptatibus officiis
              numquam. Porro, ab odio! Alias blanditiis ipsum, sed non voluptate vero.
            </Router>
          </div>
        </div>
      </Section>
    </>
  )
}

function Router({ title, children, url }: { title: string; children: string; url: string }) {
  return (
    <>
      <h3 className="mb-4 text-[24px] font-semibold text-[#1d1d1f]">{title}</h3>
      <p className="text-[#1d1d1f]">{children}</p>
      <Link href={url} target="_blank" className="rounded bg-emerald-500 px-2 py-1 text-white">
        {title}へ
      </Link>
    </>
  )
}
